// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2905fd8e181cd2f4083a615fa51f1913)
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
	// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
	interface Env {
	}
}

export interface Env extends Cloudflare.Env {
	STREAM_CONTEXT_STORE: KVNamespace
	GEMINI_API_KEY: string
	DEEPSEEK_API_KEY: string
	ANTHROPIC_API_KEY: string
	OPEN_AI_API_KEY: string
	GROQ_API_KEY: string
	DB_DEV: D1Database
}
