export enum Tags {
    "H1" = "H1",
    "H2" = "H2",
    "H3" = "H3",
    "P" = "P",
    "B" = "B",
    "I" = "I",
    "UL" = "UL",
    "OL" = "OL",
    "LI" = "LI",
    "CODE" = "CODE",
    "LANG" = "LANG",
    "CONTENT" = "CONTENT",
    "ICODE" = "ICODE",
    "QUOTE" = "QUOTE",
    "ADD" = "ADD",
    "CHECKBOX" = "CHECKBOX",
    "NODE" = "NODE",
    "DELETE" = "DELETE",
  }