name: Deploy worker to dev environment
on:
    push:
        branches:
            - dev
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                version: 8

            - name: Install dependencies
              run: pnpm install

            - name: Deploy to cloudflare dev environment
              working-directory: ./apps/worker
              run: pnpm exec wrangler deploy --env=dev
              env:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}